GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/67eb5a7802521a7ffed814d5

###


POST  http://localhost:3000/subscribers/
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Sample Channel"
}

###

DELETE http://localhost:3000/subscribers/67eb59df31fbb8c81135f018

###

PATCH http://localhost:3000/subscribers/67eb5a5d02521a7ffed814cc
Content-Type: application/json

{
    "name": "New name"
}